function beautifyAxis(hAxes)

hTitle=get(hAxes,'title');
hLegend = get(hAxes,'Legend');
hXLabel = get(hAxes,'XLabel');
hYLabel = get(hAxes, 'YLabel');


set(hAxes                      , ...
    'FontName'   , 'Arial' );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'Ariel');
set([hLegend, gca]             , ...
    'FontSize'   , 8           );
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 9.5          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );

set(hAxes, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XGrid'       , 'off'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );


 hYRuler = hAxes.YRuler;
 set(hYRuler,'Linewidth',0.25)
 set(hAxes,'GridAlpha',.08);
end